version: '3.9'

services:
  app:
    image: python:3.12-slim
    container_name: discord-wireguard
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "pip3 install --no-cache-dir -r requirements.txt && python3 main.py"